import { err, ok, type AppErrorCode, type OperationParams, type Result, type Transport } from '../types'

type WailsMethod = (...args: unknown[]) => Promise<unknown>
type WailsTable = { readonly [key: string]: WailsMethod | WailsTable | undefined }

function bindings(): Record<string, WailsTable | undefined> {
  return (globalThis as { go?: Record<string, WailsTable | undefined> }).go ?? {}
}

/**
 * Wails generates bindings as `go.<package>.<Service>.<Method>`. The gateway
 * operation is `platform.organisation.App.GetCurrent`, so the namespace is a
 * contract name rather than a Go package: the service is looked up in the
 * `main` package, which is where the transport services are registered.
 */
function resolveMethod(namespace: string, service: string, method: string): WailsMethod | undefined {
  const tables = bindings()
  for (const table of [tables[namespace], tables['main']]) {
    if (table === undefined) {
      continue
    }
    const serviceTable = table[service]
    if (serviceTable === undefined || typeof serviceTable === 'function') {
      continue
    }
    const fn = serviceTable[method]
    if (typeof fn === 'function') {
      return fn
    }
  }
  return undefined
}

/**
 * DesktopTransport dispatches through the Wails bindings generated by
 * `wails3 generate bindings`. It is the Mode A implementation of Transport.
 */
export function createDesktopTransport(): Transport {
  return {
    async call<T>(operation: string, params?: OperationParams): Promise<Result<T>> {
      const [namespace, service, method] = operation.split('.')
      if (namespace === undefined || service === undefined || method === undefined) {
        return err('INTERNAL', `malformed operation: ${operation}`)
      }

      const fn = resolveMethod(namespace, service, method)
      if (fn === undefined) {
        return err('INTERNAL', `wails binding unavailable for ${operation}`)
      }

      try {
        // A method that takes no request is called with no argument at all. Sending
        // an empty object to it would be one argument too many, which Wails rejects
        // before the transport ever sees the call.
        const call = params === undefined ? fn() : fn(params)
        return unwrapResult<T>(await call, operation)
      } catch (cause) {
        return err('INTERNAL', cause instanceof Error ? cause.message : 'desktop call failed')
      }
    },
  }
}

/**
 * Go services return the same Result envelope the interface expects, so a
 * failure arrives as a value rather than as a thrown error.
 */
function unwrapResult<T>(raw: unknown, operation: string): Result<T> {
  if (isEnvelope(raw)) {
    if (raw.ok) {
      return ok(raw.value as T)
    }
    const failure = raw.error
    if (failure !== undefined) {
      return err(toErrorCode(failure.code), failure.message, failure.details)
    }
    return err('INTERNAL', `empty failure for ${operation}`)
  }
  if (isWireError(raw)) {
    return err(toErrorCode(raw.code), raw.message, raw.details)
  }
  return err('INTERNAL', `malformed response for ${operation}`)
}

interface Envelope {
  readonly ok: boolean
  readonly value?: unknown
  readonly error?: WireError
}

function isEnvelope(value: unknown): value is Envelope {
  if (typeof value !== 'object' || value === null) {
    return false
  }
  const candidate = value as { ok?: unknown; error?: unknown }
  if (typeof candidate.ok !== 'boolean') {
    return false
  }
  return candidate.ok === true || isWireError(candidate.error)
}

interface WireError {
  readonly code: string
  readonly message: string
  readonly details?: Record<string, unknown>
}

function isWireError(value: unknown): value is WireError {
  if (typeof value !== 'object' || value === null) {
    return false
  }
  const candidate = value as { code?: unknown; message?: unknown }
  return typeof candidate.code === 'string' && typeof candidate.message === 'string'
}

function toErrorCode(code: string): AppErrorCode {
  return Object.prototype.hasOwnProperty.call(ERROR_CODES, code) ? (code as AppErrorCode) : 'INTERNAL'
}

const ERROR_CODES: Record<string, true> = {
  INSUFFICIENT_PERMISSION: true,
  UNAUTHENTICATED: true,
  PERIOD_CLOSED: true,
  INVOICE_ALREADY_POSTED: true,
  PAYMENT_ALREADY_REVERSED: true,
  INVALID_ALLOCATION: true,
  UNBALANCED_JOURNAL: true,
  STOCK_INSUFFICIENT: true,
  PAYROLL_LOCKED: true,
  VALIDATION_FAILED: true,
  NOT_FOUND: true,
  CONFLICT: true,
  ALREADY_EXISTS: true,
  NETWORK: true,
  INTERNAL: true,
}

export function isDesktopRuntime(): boolean {
  return 'go' in globalThis
}
