import type {
  AcademicYear,
  Household,
  Person,
  PersonRole,
  Relationship,
  Term,
} from '../types'

/**
 * Preview fixtures. The shapes are the wire shapes, not the domain shapes, so
 * that a screen which renders these correctly is exercising the same contract it
 * will meet in production.
 *
 * The school is deliberately a mix: a person who is both a teacher and a parent,
 * a student whose father is an employee rather than a stay-at-home guardian, a
 * leaver who is kept on file, and a household with a single billing party. Those
 * are the cases that break naive screens.
 */

const YEAR_ID = 'year-2025-2026'

export const FIXTURE_ACADEMIC_YEAR: AcademicYear = {
  id: YEAR_ID,
  organisationId: 'org-1',
  name: '2025-2026',
  startsOn: '2025-09-01',
  endsOn: '2026-07-31',
  isCurrent: true,
}

export const FIXTURE_TERMS: readonly Term[] = [
  { id: 'term-1', academicYearId: YEAR_ID, name: 'First Term', sequence: 1, startsOn: '2025-09-01', endsOn: '2025-12-19' },
  { id: 'term-2', academicYearId: YEAR_ID, name: 'Second Term', sequence: 2, startsOn: '2026-01-05', endsOn: '2026-04-03' },
  { id: 'term-3', academicYearId: YEAR_ID, name: 'Third Term', sequence: 3, startsOn: '2026-04-20', endsOn: '2026-07-31' },
]

function role(partial: Omit<PersonRole, 'academicYearId' | 'isCurrent'>): PersonRole {
  return { ...partial, academicYearId: YEAR_ID, isCurrent: true }
}

const ROLES: readonly PersonRole[] = [
  role({
    id: 'role-1',
    personId: 'person-1',
    role: 'STUDENT',
    startsOn: '2025-09-01',
    endsOn: '',
    student: {
      studentNumber: 'STU-0001',
      status: 'ENROLLED',
      admissionDate: '2015-09-08',
      previousSchool: 'École publique de Bonapriso',
      isBoarding: true,
    },
  }),
  role({
    id: 'role-2',
    personId: 'person-1',
    role: 'GUARDIAN',
    startsOn: '2025-09-01',
    endsOn: '',
    guardian: {
      isEmergencyContact: true,
      mayCollectStudent: true,
      isBillingContact: true,
      canAuthoriseMedical: true,
    },
  }),
  role({
    id: 'role-3',
    personId: 'person-2',
    role: 'EMPLOYEE',
    startsOn: '2019-09-02',
    endsOn: '',
    employee: {
      employeeNumber: 'EMP-0042',
      jobTitle: 'Mathematics Teacher',
      department: 'Mathematics',
      hiredOn: '2019-09-02',
      endedOn: '',
      contractType: 'PERMANENT',
      payrollGroup: 'Teaching',
    },
  }),
  role({
    id: 'role-4',
    personId: 'person-3',
    role: 'STUDENT',
    startsOn: '2025-09-01',
    endsOn: '',
    student: {
      studentNumber: 'STU-0002',
      status: 'ENROLLED',
      admissionDate: '2020-09-07',
      previousSchool: '',
      isBoarding: false,
    },
  }),
  role({
    id: 'role-5',
    personId: 'person-4',
    role: 'EMPLOYEE',
    startsOn: '2021-01-11',
    endsOn: '',
    employee: {
      employeeNumber: 'EMP-0107',
      jobTitle: 'Head of Admissions',
      department: 'Administration',
      hiredOn: '2021-01-11',
      endedOn: '',
      contractType: 'PERMANENT',
      payrollGroup: 'Administration',
    },
  }),
  role({
    id: 'role-6',
    personId: 'person-5',
    role: 'EMPLOYEE',
    startsOn: '2023-09-04',
    endsOn: '',
    employee: {
      employeeNumber: 'EMP-0233',
      jobTitle: 'Science Teacher',
      department: 'Biology',
      hiredOn: '2023-09-04',
      endedOn: '',
      contractType: 'FIXED_TERM',
      payrollGroup: 'Teaching',
    },
  }),
  role({
    id: 'role-7',
    personId: 'person-6',
    role: 'STUDENT',
    startsOn: '2025-09-01',
    endsOn: '',
    student: {
      studentNumber: 'STU-0003',
      status: 'ENROLLED',
      admissionDate: '2021-09-06',
      previousSchool: 'Complexe Scolaire Bilingue',
      isBoarding: false,
    },
  }),
  role({
    id: 'role-8',
    personId: 'person-7',
    role: 'STUDENT',
    startsOn: '2025-09-01',
    endsOn: '',
    student: {
      studentNumber: 'STU-0004',
      status: 'PROBATION',
      admissionDate: '2025-09-01',
      previousSchool: '',
      isBoarding: true,
    },
  }),
  // A supplier contact has no profile in Core: the supplier itself belongs to
  // Finance, which reads the person this role points at.
  role({ id: 'role-9', personId: 'person-8', role: 'SUPPLIER_CONTACT', startsOn: '2024-01-15', endsOn: '' }),
  role({
    id: 'role-10',
    personId: 'person-9',
    role: 'EMPLOYEE',
    startsOn: '2018-09-03',
    endsOn: '',
    employee: {
      employeeNumber: 'EMP-0011',
      jobTitle: 'Bursar',
      department: 'Finance',
      hiredOn: '2018-09-03',
      // A leaver keeps the record: the department they worked in is a fact about
      // the past that a payslip still needs.
      endedOn: '2026-03-31',
      contractType: 'PERMANENT',
      payrollGroup: 'Administration',
    },
  }),
]

function person(partial: Omit<Person, 'roles' | 'guardiansOf' | 'guardianOf' | 'organisationId'>): Person {
  return {
    ...partial,
    organisationId: 'org-1',
    roles: ROLES.filter((role) => role.personId === partial.id),
    guardiansOf: [],
    guardianOf: [],
  }
}

export const FIXTURE_PEOPLE: readonly Person[] = [
  person({
    id: 'person-1',
    firstName: 'Amina',
    middleName: '',
    lastName: 'Njoya',
    preferredName: '',
    displayName: 'Amina Njoya',
    email: 'amina.njoya@example.test',
    phone: '+237 6 77 21 40 15',
    secondaryPhone: '',
    dateOfBirth: '2011-03-14',
    gender: 'FEMALE',
    nationality: 'Cameroonian',
    nationalId: 'CMR-2011-4471',
    address: { line1: 'Rue 12, Bonapriso', line2: '', city: 'Douala', postalCode: '', country: 'CM' },
    photoDocumentId: '',
    isActive: true,
  }),
  person({
    id: 'person-2',
    firstName: 'Joseph',
    middleName: 'Marie',
    lastName: 'Mbarga',
    preferredName: 'Jo',
    displayName: 'Jo Mbarga',
    email: 'j.mbarga@akwagroupe.test',
    phone: '+237 6 99 04 77 12',
    secondaryPhone: '',
    dateOfBirth: '1984-11-02',
    gender: 'MALE',
    nationality: 'Cameroonian',
    nationalId: 'CMR-1984-1108',
    address: { line1: 'Rue Koloko', line2: 'BP 4471', city: 'Douala', postalCode: '', country: 'CM' },
    photoDocumentId: '',
    isActive: true,
  }),
  person({
    id: 'person-3',
    firstName: 'Junior',
    middleName: '',
    lastName: 'Mbarga',
    preferredName: '',
    displayName: 'Junior Mbarga',
    email: '',
    phone: '',
    secondaryPhone: '',
    dateOfBirth: '2013-06-30',
    gender: 'MALE',
    nationality: 'Cameroonian',
    nationalId: '',
    address: { line1: 'Rue Koloko', line2: 'BP 4471', city: 'Douala', postalCode: '', country: 'CM' },
    photoDocumentId: '',
    isActive: true,
  }),
  person({
    id: 'person-4',
    firstName: 'Paul',
    middleName: '',
    lastName: 'Owona',
    preferredName: '',
    displayName: 'Paul Owona',
    email: 'paul.owona@akwagroupe.test',
    phone: '+237 6 78 55 12 90',
    secondaryPhone: '+237 2 33 42 10 08',
    dateOfBirth: '1979-01-19',
    gender: 'MALE',
    nationality: 'Cameroonian',
    nationalId: 'CMR-1979-2201',
    address: { line1: 'Avenue du Centre', line2: 'BP 22', city: 'Douala', postalCode: '00200', country: 'CM' },
    photoDocumentId: '',
    isActive: true,
  }),
  person({
    id: 'person-5',
    firstName: 'Estelle',
    middleName: '',
    lastName: 'Ngo Bell',
    preferredName: '',
    displayName: 'Estelle Ngo Bell',
    email: 'e.ngobell@akwagroupe.test',
    phone: '+237 6 90 33 21 04',
    secondaryPhone: '',
    dateOfBirth: '1990-08-25',
    gender: 'FEMALE',
    nationality: 'Cameroonian',
    nationalId: 'CMR-1990-3312',
    address: { line1: 'Rue Njo-Njo', line2: '', city: 'Douala', postalCode: '', country: 'CM' },
    photoDocumentId: '',
    isActive: true,
  }),
  person({
    id: 'person-6',
    firstName: 'Alice',
    middleName: '',
    lastName: 'Owona',
    preferredName: '',
    displayName: 'Alice Owona',
    email: '',
    phone: '',
    secondaryPhone: '',
    dateOfBirth: '2012-02-08',
    gender: 'FEMALE',
    nationality: 'Cameroonian',
    nationalId: '',
    address: { line1: 'Avenue du Centre', line2: 'BP 22', city: 'Douala', postalCode: '00200', country: 'CM' },
    photoDocumentId: '',
    isActive: true,
  }),
  person({
    id: 'person-7',
    firstName: 'Blaise',
    middleName: '',
    lastName: 'Fotso',
    preferredName: '',
    displayName: 'Blaise Fotso',
    email: '',
    phone: '',
    secondaryPhone: '',
    dateOfBirth: '2013-09-17',
    gender: 'MALE',
    nationality: 'Cameroonian',
    nationalId: '',
    address: { line1: 'Quartier Bali', line2: '', city: 'Douala', postalCode: '', country: 'CM' },
    photoDocumentId: '',
    isActive: false,
  }),
  person({
    id: 'person-8',
    firstName: 'Damien',
    middleName: '',
    lastName: 'Fotso',
    preferredName: '',
    displayName: 'Damien Fotso',
    email: 'contact@fotso-sarl.test',
    phone: '+237 6 96 14 77 03',
    secondaryPhone: '',
    dateOfBirth: '1975-04-03',
    gender: 'MALE',
    nationality: 'Cameroonian',
    nationalId: 'CMR-1975-0904',
    address: { line1: 'Zone Industrielle Bassa', line2: '', city: 'Douala', postalCode: '', country: 'CM' },
    photoDocumentId: '',
    isActive: true,
  }),
  person({
    id: 'person-9',
    firstName: 'Marthe',
    middleName: '',
    lastName: 'Ekwe',
    preferredName: '',
    displayName: 'Marthe Ekwe',
    email: 'm.ekwe@akwagroupe.test',
    phone: '+237 6 55 09 88 20',
    secondaryPhone: '',
    dateOfBirth: '1972-12-11',
    gender: 'FEMALE',
    nationality: 'Cameroonian',
    nationalId: 'CMR-1972-5520',
    address: { line1: 'Rue Bali', line2: '', city: 'Douala', postalCode: '', country: 'CM' },
    photoDocumentId: '',
    isActive: true,
  }),
]

export const FIXTURE_RELATIONSHIPS: readonly Relationship[] = [
  {
    id: 'rel-1',
    academicYearId: YEAR_ID,
    fromPersonId: 'person-2',
    toPersonId: 'person-3',
    type: 'GUARDIAN_OF',
    role: 'FATHER',
    isPrimary: true,
    isActive: true,
  },
  {
    id: 'rel-2',
    academicYearId: YEAR_ID,
    fromPersonId: 'person-1',
    toPersonId: 'person-2',
    type: 'GUARDIAN_OF',
    role: 'PARENT',
    isPrimary: false,
    isActive: true,
  },
  {
    id: 'rel-3',
    academicYearId: YEAR_ID,
    fromPersonId: 'person-2',
    toPersonId: 'person-1',
    type: 'EMERGENCY_CONTACT_OF',
    role: '',
    isPrimary: true,
    isActive: true,
  },
  {
    id: 'rel-4',
    academicYearId: YEAR_ID,
    fromPersonId: 'person-4',
    toPersonId: 'person-6',
    type: 'GUARDIAN_OF',
    role: 'FATHER',
    isPrimary: true,
    isActive: true,
  },
  {
    id: 'rel-5',
    academicYearId: YEAR_ID,
    fromPersonId: 'person-9',
    toPersonId: 'person-7',
    type: 'GUARDIAN_OF',
    role: 'MOTHER',
    isPrimary: true,
    // Deactivated rather than deleted: a statement printed last term still
    // resolves the guardian who was on it.
    isActive: false,
  },
]

export const FIXTURE_HOUSEHOLDS: readonly Household[] = [
  {
    id: 'household-1',
    academicYearId: YEAR_ID,
    name: 'Owona family',
    billingEmail: 'paul.owona@example.test',
    billingPhone: '+237 6 78 55 12 90',
    billingAddress: { line1: 'Avenue du Centre', line2: 'BP 22', city: 'Douala', postalCode: '00200', country: 'CM' },
    members: [
      { personId: 'person-4', role: 'HEAD', isBillingPart: true },
      { personId: 'person-6', role: 'DEPENDENT', isBillingPart: false },
    ],
  },
  {
    id: 'household-2',
    academicYearId: YEAR_ID,
    name: 'Mbarga family',
    billingEmail: 'j.mbarga@akwagroupe.test',
    billingPhone: '+237 6 99 04 77 12',
    billingAddress: { line1: 'Rue Koloko', line2: 'BP 4471', city: 'Douala', postalCode: '', country: 'CM' },
    members: [
      { personId: 'person-2', role: 'HEAD', isBillingPart: true },
      { personId: 'person-1', role: 'DEPENDENT', isBillingPart: false },
      { personId: 'person-3', role: 'DEPENDENT', isBillingPart: false },
    ],
  },
]
